import Head from 'next/head'
import React from 'react'
import LeftSide from './LeftSide'
import RigthSide from './RigthSide'
import Footer from './Footer'

function Layout({ children, title }) {
    return (
        <>
            <Head>
                <title>{title ? title + " - Ariel Paixão" : "Ariel Paixão"}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='flex justify-between'>
                <LeftSide />
                {children}
                <RigthSide />
            </div>
            <Footer />
        </>
    )
}

export default Layout